version: "3.7"
services:
  database:
    build:
      dockerfile: db.Dockerfile
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=fantasy-user
      - POSTGRES_PASSWORD=fantasy-pwd
      - POSTGRES_DB=fantasy-db
  hydration:
    build:
      dockerfile: php.Dockerfile
      target: dev
    volumes:
      - ./:/app
