version: "3.7"
services:
  database:
    image: postgres:14-alpine
    container_name: database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=fantasy-user
      - POSTGRES_PASSWORD=fantasy-pwd
      - POSTGRES_DB=fantasy-db
  hydration:
    container_name: hydration
    build:
      dockerfile: php.Dockerfile
    volumes:
      - ./:/app
