version: "3"
services:
  database:
    image: postgres
    container_name: database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  hydration:
    container_name: hydration
    build:
      dockerfile: php.Dockerfile
    volumes:
      - ./:/app
